import { readFile, rename } from "node:fs/promises";
import { join, resolve } from "node:path";
import { gunzipSync } from "node:zlib";

import {
  chromium,
  expect,
  test,
  type Browser,
  type BrowserContext,
  type Page,
} from "@playwright/test";

import { enterMultiplayerLobby, findGameIdByCreatorNickname } from "./support";

const playerCount = 4;
const recordingDirectory = "playwright_adhoc/multiplayer-full-run";

type RecordedPlayer = {
  readonly context: BrowserContext;
  readonly page: Page;
  readonly videoPath: Promise<string> | undefined;
};

type RecordedInputRun = {
  readonly count: number;
  readonly horizontal: "left" | "right" | "neutral";
  readonly jump: boolean;
  readonly down: boolean;
  readonly run: boolean;
};

const world11FrameMilliseconds = 1000 / 60;

async function readWorld11SmallInputTrace(): Promise<
  readonly RecordedInputRun[]
> {
  const serialized = await readFile(
    resolve(
      process.cwd(),
      "tests/multiplayer-browser/world11-small-input-trace.json.gz.base64",
    ),
    "utf8",
  );
  return JSON.parse(
    gunzipSync(Buffer.from(serialized.trim(), "base64")).toString("utf8"),
  ) as readonly RecordedInputRun[];
}

async function replayRecordedWorld11Input(
  player: RecordedPlayer,
): Promise<void> {
  await releaseRunningKeys(player);
  await player.page.getByLabel("Authoritative multiplayer game view").focus();
  let held = {
    left: false,
    right: false,
    jump: false,
    down: false,
    run: false,
  };
  const startedAtMilliseconds = performance.now();
  let scheduledFrames = 0;
  for (const input of await readWorld11SmallInputTrace()) {
    const next = {
      left: input.horizontal === "left",
      right: input.horizontal === "right",
      jump: input.jump,
      down: input.down,
      run: input.run,
    };
    const edges: readonly [key: string, wasHeld: boolean, nowHeld: boolean][] =
      [
        ["ArrowLeft", held.left, next.left],
        ["ArrowRight", held.right, next.right],
        ["Space", held.jump, next.jump],
        ["ArrowDown", held.down, next.down],
        ["ShiftLeft", held.run, next.run],
      ];
    for (const [key, wasHeld, nowHeld] of edges) {
      if (wasHeld && !nowHeld) await player.page.keyboard.up(key);
      if (!wasHeld && nowHeld) await player.page.keyboard.down(key);
    }
    held = next;
    scheduledFrames += input.count;
    // Key transitions themselves take measurable wall time. Waiting until an
    // absolute deadline preserves the 60 Hz core trace instead of accumulating
    // that transport overhead into a progressively late platforming replay.
    const remainingMilliseconds =
      scheduledFrames * world11FrameMilliseconds -
      (performance.now() - startedAtMilliseconds);
    if (remainingMilliseconds > 0) {
      await player.page.waitForTimeout(remainingMilliseconds);
    }
  }
  await releaseRunningKeys(player);
}

async function makeRecordedPlayer(
  browser: Browser,
  index: number,
): Promise<RecordedPlayer> {
  const context = await browser.newContext({
    recordVideo: {
      dir: recordingDirectory,
      size: { width: 1280, height: 720 },
    },
    viewport: { width: 1280, height: 720 },
  });
  const page = await context.newPage();
  await enterMultiplayerLobby(page);
  await page.getByLabel("Nickname").fill(`RunPlayer${String(index + 1)}`);
  await page.getByRole("button", { name: "Save profile" }).click();
  await expect(
    page.locator('main[data-role="multiplayer"]'),
  ).not.toHaveAttribute("aria-busy", "true");
  return { context, page, videoPath: page.video()?.path() };
}

async function closeAndNameRecording(
  player: RecordedPlayer,
  index: number,
): Promise<void> {
  await player.context.close();
  if (player.videoPath === undefined) {
    throw new Error("Playwright did not create a player recording.");
  }
  await rename(
    await player.videoPath,
    join(recordingDirectory, `player-${String(index + 1)}.webm`),
  );
}

async function releaseRunningKeys(player: RecordedPlayer): Promise<void> {
  await player.page.keyboard.up("ArrowLeft");
  await player.page.keyboard.up("ArrowRight");
  await player.page.keyboard.up("ArrowDown");
  await player.page.keyboard.up("ShiftLeft");
  await player.page.keyboard.up("Space");
}

async function stopRunning(players: readonly RecordedPlayer[]): Promise<void> {
  await Promise.all(
    players.map(async (player) => {
      await releaseRunningKeys(player);
    }),
  );
}

async function runAndJumpToExit(
  players: readonly RecordedPlayer[],
): Promise<void> {
  const replayLeader = players[0];
  if (replayLeader === undefined)
    throw new Error("Recording replay leader is missing.");
  // This trace was generated by the deterministic core's normal small-player
  // World 1-1 completion (zero resets). It is replayed exclusively as physical
  // browser keyboard edges against the production WebSocket server: no state
  // is injected into a client or the authoritative simulation.
  await replayRecordedWorld11Input(replayLeader);
  await replayLeader.page.waitForTimeout(1_000);
}

test.setTimeout(300_000);

test("four separate browser sessions complete a shared course and enter the next", async () => {
  const browsers = await Promise.all(
    Array.from({ length: playerCount }, () => chromium.launch()),
  );
  const players = await Promise.all(
    browsers.map((browser, index) => makeRecordedPlayer(browser, index)),
  );
  try {
    const creator = players[0];
    if (creator === undefined) {
      throw new Error("Recorded creator is missing.");
    }
    await creator.page.getByLabel("Bundled level").selectOption("smb-1-1");
    await creator.page.getByRole("button", { name: "Create game" }).click();
    const gameId = await findGameIdByCreatorNickname(
      creator.page,
      "RunPlayer1",
    );
    for (const player of players.slice(1)) {
      await player.page.reload();
      await player.page.getByRole("button", { name: "Join" }).click();
    }
    await creator.page.getByRole("button", { name: "Start game" }).click();
    await Promise.all(
      players.map((player) =>
        expect(
          player.page.getByLabel("Authoritative multiplayer game view"),
        ).toBeVisible(),
      ),
    );
    // The canvas is created while the game is still waiting. Do not send a
    // real player's first held movement command until every separate browser
    // has received the authoritative playing state; inputs submitted during
    // the waiting transition are intentionally not gameplay commands.
    await Promise.all(
      players.map((player) =>
        expect(
          player.page.locator(".multiplayer-play-controls-only p").first(),
        ).toHaveText(/^playing · frame [1-9][0-9]*$/),
      ),
    );
    await expect(
      creator.page.getByLabel("Authoritative multiplayer game view"),
    ).toHaveAttribute("data-authoritative-level-id", "smb-1-1");
    await Promise.all(
      players.map(async (player) => {
        const canvas = player.page.getByLabel(
          "Authoritative multiplayer game view",
        );
        await expect(canvas).toHaveAttribute(
          "data-authoritative-player-count",
          String(playerCount),
        );
        await expect(canvas).toHaveAttribute(
          "data-authoritative-simulation-player-count",
          String(playerCount),
        );
        await expect(canvas).toHaveAttribute(
          "data-rendered-coop-player-count",
          String(playerCount - 1),
        );
      }),
    );
    await Promise.all(
      players.map((player, index) =>
        player.page.screenshot({
          path: join(
            recordingDirectory,
            `player-${String(index + 1)}-smb-1-1.png`,
          ),
        }),
      ),
    );
    const gameShell = creator.page.locator(".multiplayer-game-shell");
    const canvas = creator.page.getByLabel(
      "Authoritative multiplayer game view",
    );
    const canvasBox = await canvas.boundingBox();
    if (canvasBox === null) {
      throw new Error("Multiplayer canvas layout box is unavailable.");
    }
    await expect(gameShell).toHaveAttribute("data-controls-open", "false");
    expect(canvasBox).toMatchObject({ x: 0, y: 0, width: 1280, height: 720 });

    await runAndJumpToExit(players);

    await expect(
      creator.page.getByLabel("Authoritative multiplayer game view"),
    ).toHaveAttribute("data-authoritative-level-id", "smb-1-2", {
      timeout: 20_000,
    });
    await stopRunning(players);
    await creator.page.waitForTimeout(350);
    const nextLevelSnapshot = await creator.page.request.get(
      `/api/games/${gameId}/snapshot`,
      { headers: { "x-multiplayer-protocol-version": "1" } },
    );
    const nextLevelSnapshotBody = (await nextLevelSnapshot.json()) as {
      readonly levelId: string;
      readonly players: readonly unknown[];
    };
    expect(nextLevelSnapshotBody.levelId).toBe("smb-1-2");
    expect(nextLevelSnapshotBody.players).toHaveLength(playerCount);

    // A level handoff rebuilds the authoritative-render Phaser scene in every
    // browser. All independently recorded clients must render the real next
    // shared course before this accepted first-course completion is recorded.
    await Promise.all(
      players.map((player) =>
        expect(
          player.page.getByLabel("Authoritative multiplayer game view"),
        ).toHaveAttribute("data-authoritative-level-id", "smb-1-2"),
      ),
    );
    await stopRunning(players);
    await expect(
      creator.page.getByLabel("Authoritative multiplayer game view"),
    ).toHaveAttribute("data-authoritative-level-id", "smb-1-2", {
      timeout: 5_000,
    });
    await creator.page.waitForTimeout(1_000);
    await Promise.all(
      players.map(async (player) => {
        const frame = await player.page
          .getByLabel("Authoritative multiplayer game view")
          .getAttribute("data-authoritative-frame");
        expect(Number(frame)).toBeGreaterThan(12);
        await expect(
          player.page.locator(".multiplayer-play-controls-only h1"),
        ).toHaveText(/Game game-1 · smb-1-2/);
      }),
    );
    const finalCanvasBoxes = await Promise.all(
      players.map((player) =>
        player.page
          .getByLabel("Authoritative multiplayer game view")
          .boundingBox(),
      ),
    );
    for (const [index, box] of finalCanvasBoxes.entries()) {
      if (box === null) {
        throw new Error("A final multiplayer canvas is unavailable.");
      }
      expect(box.x, `player ${String(index + 1)}`).toBe(0);
      expect(box.y, `player ${String(index + 1)}`).toBe(0);
      expect(box.width, `player ${String(index + 1)}`).toBe(1280);
      expect(box.height, `player ${String(index + 1)}`).toBe(720);
    }
    await Promise.all(
      players.map(async (player, index) => {
        const canvas = player.page.getByLabel(
          "Authoritative multiplayer game view",
        );
        expect(
          await canvas.getAttribute("width"),
          `player ${String(index + 1)}`,
        ).toBe("1280");
        expect(
          await canvas.getAttribute("height"),
          `player ${String(index + 1)}`,
        ).toBe("720");
      }),
    );

    await Promise.all(
      players.map((player, index) =>
        player.page.screenshot({
          path: join(
            recordingDirectory,
            `player-${String(index + 1)}-smb-1-2.png`,
          ),
        }),
      ),
    );
    await Promise.all(
      players.map((player) =>
        expect(
          player.page.getByLabel("Authoritative multiplayer game view"),
        ).toHaveAttribute("data-authoritative-level-id", "smb-1-2"),
      ),
    );
    await creator.page.keyboard.press("KeyM");
    await expect(
      creator.page.getByRole("button", { name: "End game", exact: true }),
    ).toBeVisible();
    await creator.page
      .getByRole("button", { name: "End game", exact: true })
      .click();
  } finally {
    await Promise.all(players.map(closeAndNameRecording));
    await Promise.all(browsers.map((browser) => browser.close()));
  }
});
